### ISSUE TITLE
calloc does not check for overflow

### ISSUE THREAD

**Issue by graphitemaster** [ttvd/moreram-osx#1]
As required by the spec, when `n*m` cannot be represented as `size_t`, then `errno` must be set to `ENOMEM` and return `NULL` In moreram this is tested fairly early on as

```
if (n && m > (size_t)-1/n) {
    errno = ENOMEM;
    return 0;
}
```

**Comment by ttvd** [comment]
Fixed in dd7c5fbf1820885d27544727e2322f2847f7f2e4 .
