### ISSUE TITLE
Not thread safe

### ISSUE THREAD

**Issue by graphitemaster** [ttvd/moreram-osx#2]
Since C11 and C++11 the standards require `malloc`, `calloc`, `realloc`, and `free` to be thread safe. This project does not hold any locks when manipulating the linked-list that represents the Metal heap.

**Comment by graphitemaster** [comment]
Actually it appears it does hold locks, just not for `malloc`

**Comment by ttvd** [comment]
Fixed in dbe5f00a7293b391c4ffe2b8601c8cf5de933c38 .
