### ISSUE TITLE
Linked-list heap backed by libc malloc

### ISSUE THREAD

**Issue by graphitemaster** [ttvd/moreram-osx#3]
The logic of moreram is to allocate from GPU heap on OOM. This project allocates the linked-list structure using standard libc `malloc` which is going to return `NULL` due to oom (indicated by `ENOMEM` in `errno`). In general the linked-list structure has to be represented with the memory backed by the GPU, this project does not do this.

**Comment by ttvd** [comment]
Addressed in b36ecacbd4ddf36423c59259ed4824935bbca414 .
