### ISSUE TITLE
Calloc spuriously causes page-faults

### ISSUE THREAD

**Issue by graphitemaster** [ttvd/moreram-osx#4]
Not your fault since my project made the same mistake. Most memory backed by the IOMMU of the GPU and also the kernel is just a contigious arrangment of the zero-page specified by page table entries. It's not until you actually write to the page that it allocates real backing pages. There are two choices here. Choice 1 (which is what you're doing) to set it all to zero. Effectively commiting it to memory - at the cost of a ton of page-faults. Or choice 2 (which is what I do now) to only write zeros if they words are not already zero. This means pages that are referencing the zero-page don't issue page-faults and wont get comitted to memory, and pages that are dirty get set to zero. Overall it makes things faster. Good malloc implementations (like the one in libc) does what I'm now doing.

**Comment by graphitemaster** [comment]
Actually looking at the Metal spec it states
`A new buffer object with a new memory allocation. The buffer’s data is initially filled with zeroes.`
So the `memset` is wasting lots of bandwidth, can probably just remove it.

**Comment by ttvd** [comment]
Good catch, addressed in 7eead4fbdb9fec2e3775554664bb29b1f45f7dc4 .
